# Generated by Django 6.0.6 on 2026-07-06 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=32, unique=True)),
                ('grade_level', models.CharField(choices=[('grade_1_primary', 'Grade 1 Primary'), ('grade_2_primary', 'Grade 2 Primary'), ('grade_3_primary', 'Grade 3 Primary'), ('grade_4_primary', 'Grade 4 Primary'), ('grade_5_primary', 'Grade 5 Primary'), ('grade_6_primary', 'Grade 6 Primary'), ('grade_1_preparatory', 'Grade 1 Preparatory'), ('grade_2_preparatory', 'Grade 2 Preparatory'), ('grade_3_preparatory', 'Grade 3 Preparatory'), ('grade_1_secondary', 'Grade 1 Secondary'), ('grade_2_secondary', 'Grade 2 Secondary'), ('grade_3_secondary', 'Grade 3 Secondary')], max_length=32)),
                ('branch', models.CharField(choices=[('general', 'General'), ('science', 'Science'), ('literary', 'Literary')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='accounts.accountprofile')),
            ],
            options={
                'ordering': ['student_code'],
                'indexes': [models.Index(fields=['student_code'], name='students_st_student_5e7a7e_idx'), models.Index(fields=['status'], name='students_st_status_5e2210_idx'), models.Index(fields=['grade_level', 'branch'], name='students_st_grade_l_6817ad_idx')],
            },
        ),
    ]
