# Generated by Django 6.0.6 on 2026-07-06 23:14

import novaplatform_backend.upload_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_role_custom_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=novaplatform_backend.upload_security.profile_photo_upload_to, validators=[novaplatform_backend.upload_security.validate_profile_photo]),
        ),
    ]
