# Generated by Django 6.0.6 on 2026-07-06 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountprofile_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('edit', 'Edit'), ('delete', 'Delete'), ('payment', 'Payment')], max_length=20)),
                ('target_model', models.CharField(max_length=120)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='accounts_ac_event_t_7f659f_idx'), models.Index(fields=['target_model', 'target_id'], name='accounts_ac_target__7c28d5_idx')],
            },
        ),
    ]
