# Generated by Django 6.0.6 on 2026-07-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_loginsecurity_ip_and_loginattemptlog_hardening'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginattemptlog',
            new_name='accounts_lo_usernam_3ba642_idx',
            old_name='accounts_lo_username_6f88b4_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattemptlog',
            new_name='accounts_lo_is_succ_4257fa_idx',
            old_name='accounts_lo_is_succ_278c84_idx',
        ),
        migrations.RenameIndex(
            model_name='loginsecurity',
            new_name='accounts_lo_is_lock_1dd9e0_idx',
            old_name='accounts_lo_is_lock_6312db_idx',
        ),
        migrations.RenameIndex(
            model_name='loginsecurity',
            new_name='accounts_lo_locked__0a96af_idx',
            old_name='accounts_lo_locked__26c3cf_idx',
        ),
    ]
