# Generated by Django 6.0.6 on 2026-07-08 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_accounts_lo_username_6f88b4_idx_accounts_lo_usernam_3ba642_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginIPBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('first_failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('one_ip_multiple_usernames', 'One IP Multiple Usernames'), ('one_username_multiple_ips', 'One Username Multiple IPs')], max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('window_seconds', models.PositiveIntegerField(default=900)),
                ('threshold', models.PositiveIntegerField(default=0)),
                ('observed_count', models.PositiveIntegerField(default=0)),
                ('sample_count', models.PositiveIntegerField(default=1)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.AddField(
            model_name='loginattemptlog',
            name='is_lock_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginattemptlog',
            name='is_unlock_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginattemptlog',
            name='unlock_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loginattemptlog',
            name='unlocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlock_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginattemptlog',
            index=models.Index(fields=['ip_address', 'attempted_at'], name='accounts_lo_ip_addr_d970e9_idx'),
        ),
        migrations.AddIndex(
            model_name='loginipblock',
            index=models.Index(fields=['blocked_until'], name='accounts_lo_blocked_39a53e_idx'),
        ),
        migrations.AddIndex(
            model_name='loginipblock',
            index=models.Index(fields=['last_failed_at'], name='accounts_lo_last_fa_fa35db_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['event_type', 'last_seen_at'], name='accounts_su_event_t_28263d_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['ip_address', 'last_seen_at'], name='accounts_su_ip_addr_75a9db_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['username', 'last_seen_at'], name='accounts_su_usernam_4f44c4_idx'),
        ),
    ]
