# Generated by Django 6.0.6 on 2026-07-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at'], 'permissions': [('publish_exam', 'Can publish exam'), ('unpublish_exam', 'Can unpublish exam')]},
        ),
    ]
