# Generated by Django 6.0.6 on 2026-07-06 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=32, unique=True)),
                ('specialization', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('hired_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='accounts.accountprofile')),
            ],
            options={
                'ordering': ['employee_code'],
                'indexes': [models.Index(fields=['employee_code'], name='teachers_te_employe_1ea117_idx'), models.Index(fields=['status'], name='teachers_te_status_cc7a79_idx'), models.Index(fields=['specialization'], name='teachers_te_special_40f7e8_idx')],
            },
        ),
    ]
