# Generated by Django 6.0.6 on 2026-07-06 23:14

import django.db.models.deletion
import novaplatform_backend.upload_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_course_category_lesson_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('attachment', models.FileField(upload_to=novaplatform_backend.upload_security.homework_upload_to, validators=[novaplatform_backend.upload_security.validate_homework_attachment])),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='courses.enrollment')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_submissions', to='courses.lesson')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status'], name='courses_hom_status_ba1094_idx'), models.Index(fields=['enrollment', 'submitted_at'], name='courses_hom_enrollm_7ecb5c_idx')],
            },
        ),
    ]
